server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass https://accountant-api-v2-1002080144616.us-central1.run.app/api/;
        proxy_set_header Host accountant-api-v2-1002080144616.us-central1.run.app;
        proxy_ssl_server_name on;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
